[workspace.package]
version = "0.1.0"

[workspace]
resolver = "2"

members = [
  "kble",
  "kble-serialport",
  "kble-socket",
  "kble-c2a",
  "kble-eb90",
]

[workspace.dependencies]
anyhow = "1"
futures = "0.3"
futures-util = { version = "0.3", features = ["sink"] }
pin-project-lite = { version = "0.2" }
tokio = "1"
tokio-tungstenite = { version = "0.18" }
axum = { version = "0.6", default-features = false }
bytes = "1.4.0"
