[package]
name = "kble-serialport"
version.workspace = true
edition = "2021"
license = "MIT"
description = "Virtual Harness Toolkit"
repository = "https://github.com/arkedge/kble"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive", "env"] }
futures.workspace = true
tokio = { workspace = true, features = ["full"] }
kble-socket = { workspace = true, features = ["axum"] }
tracing.workspace = true
tracing-subscriber.workspace = true
axum = { workspace = true, default-features = false, features = ["tokio", "tower-log", "http1", "ws", "query"] }
tokio-serial = "5.4"
serde.workspace = true
bytes.workspace = true
