[package]
name = "kble-socket"
version.workspace = true
edition = "2021"
license = "MIT"
description = "Virtual Harness Toolkit"
repository = "https://github.com/arkedge/kble"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
futures-util.workspace = true
pin-project-lite = { workspace = true, optional = true }
tokio.workspace = true
tokio-tungstenite = { workspace = true, optional = true }
axum.workspace = true
bytes.workspace = true

[features]
stdio = ["tokio/io-std", "dep:pin-project-lite"]
tungstenite = ["dep:tokio-tungstenite"]
axum = ["axum/ws"]
