name: Rust

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  id-token: write
  contents: read
  checks: write
  pull-requests: write

env:
  # renovate: datasource=github-releases depName=EmbarkStudios/cargo-about
  CARGO_ABOUT_VERSION: 0.6.4

jobs:
  verify-crate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get Rust toolchain
        id: toolchain
        working-directory: .
        run: |
          awk -F'[ ="]+' '$1 == "channel" { print "toolchain=" $2 }' rust-toolchain >> "$GITHUB_OUTPUT"

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ steps.toolchain.outputs.toolchain }}
          components: clippy, rustfmt

      - name: cache dependencies
        uses: Swatinem/rust-cache@v2.7.5

      - name: install cargo-about
        run: |
          cargo install --locked cargo-about --version ${{ env.CARGO_ABOUT_VERSION }}

      - name: reviewdog / clippy
        uses: sksat/action-clippy@v1.1.1
        with:
          reporter: github-pr-review

      - name: format
        run: cargo fmt --all --check

      - name: unit test
        run: cargo test
