name: Verify Crates

on:
  workflow_call:
    inputs:
      target_dir:
        description: "cargo target dir"
        required: true
        type: string

permissions:
  id-token: write
  contents: read
  checks: write
  pull-requests: write

env:
  CARGO_INCREMENTAL: 0

jobs:
  verify-crate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.target_dir }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Get Rust toolchain
        id: toolchain
        working-directory: .
        run: |
          echo "toolchain=$(awk -F'[ ="]+' '$1 == "channel" { print $2 }' rust-toolchain)" >> "$GITHUB_OUTPUT"

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ steps.toolchain.outputs.toolchain }}
          components: clippy, rustfmt

      - name: cache dependencies
        uses: Swatinem/rust-cache@v2.2.1

      - name: reviewdog / clippy
        uses: sksat/action-clippy@v0.2.1
        with:
          working_directory: ${{ inputs.target_dir }}
          reporter: github-pr-review

      - name: format
        run: cargo fmt --all --check

      - name: unit test
        run: cargo test
