//! End-to-end tests that launch the real `kble-eb90` binary and talk to it
//! over the same WebSocket-over-stdio protocol that the `kble` orchestrator
//! uses (see `kble/src/plug.rs`). The test plays the `Role::Client` side; the
//! spawned process plays `Role::Server` via `kble_socket::from_stdio`.
//!
//! The core property under test is the codec round-trip:
//!
//! ```text
//! decode(encode(x)) == x   for all payloads x
//! ```
//!
//! That is a textbook fit for property-based testing, so the bulk of the
//! coverage is generated by `proptest`. Because each round-trip spawns two real
//! processes, the case counts are deliberately small.

use bytes::Bytes;
use kble_test_support::Plug;
use proptest::prelude::*;
use tokio::process::Command;
use tokio::runtime::Runtime;

/// Upper bound (exclusive) on generated payload lengths.
const MAX_PAYLOAD_LEN: usize = 2048;

/// `kble-eb90 decode` assembles each whole frame in a fixed-capacity buffer
/// (`eb90`'s parser never grows it past the initial capacity), so the buffer
/// must exceed the largest *encoded* frame — payload plus EB90 framing overhead.
/// A frame larger than this is never emitted, so we give generous headroom above
/// `MAX_PAYLOAD_LEN` rather than relying on the 2048-byte default.
const DECODE_BUFFER_SIZE: usize = MAX_PAYLOAD_LEN * 2;

/// Build a `Command` that runs the freshly-built `kble-eb90` binary with the
/// given subcommand. Cargo exposes the binary path to integration tests of the
/// same crate via this env var, so no `escargot`/`assert_cmd` is needed.
fn eb90(subcommand: &str) -> Command {
    let mut cmd = Command::new(env!("CARGO_BIN_EXE_kble-eb90"));
    cmd.arg(subcommand);
    cmd
}

/// Run `payload` through a fresh `encode` process and return the framed bytes.
async fn encode(payload: Bytes) -> Bytes {
    let mut enc = Plug::spawn(eb90("encode"))
        .await
        .expect("spawn kble-eb90 encode");
    enc.send(payload).await.expect("send to encode");
    let encoded = enc.recv().await.expect("encode produced a frame");
    enc.shutdown().await.expect("encode exits cleanly");
    encoded
}

/// Run `frame` through a fresh `decode` process and return the decoded payload.
async fn decode(frame: Bytes) -> Bytes {
    let mut cmd = eb90("decode");
    cmd.arg("--buffer-size").arg(DECODE_BUFFER_SIZE.to_string());
    let mut dec = Plug::spawn(cmd).await.expect("spawn kble-eb90 decode");
    dec.send(frame).await.expect("send to decode");
    let decoded = dec.recv().await.expect("decode produced a frame");
    dec.shutdown().await.expect("decode exits cleanly");
    decoded
}

/// Encode then decode `payload` through two real processes and return what
/// comes out the far end. A correct codec must return the original bytes.
async fn roundtrip(payload: &[u8]) -> Bytes {
    let encoded = encode(Bytes::copy_from_slice(payload)).await;
    decode(encoded).await
}

/// A small current-thread runtime to drive the async round-trip from inside the
/// synchronous closures that `proptest!` generates.
fn runtime() -> Runtime {
    tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .expect("build tokio runtime")
}

/// Deterministic smoke test: fast feedback and a readable failure if the
/// spawn/handshake plumbing breaks, independent of the generated cases below.
#[tokio::test]
async fn roundtrips_simple_payload() {
    let payload = b"hello, kble!";
    let decoded = roundtrip(payload).await;
    assert_eq!(decoded, &payload[..]);
}

proptest! {
    // Each case spawns two processes, so keep the count modest. Integration
    // tests have no crate-root source dir, so disable the regression file.
    #![proptest_config(ProptestConfig {
        cases: 64,
        failure_persistence: None,
        ..ProptestConfig::default()
    })]

    /// Arbitrary payloads of arbitrary bytes must round-trip unchanged.
    #[test]
    fn roundtrips_arbitrary_payload(payload in proptest::collection::vec(any::<u8>(), 1..MAX_PAYLOAD_LEN)) {
        let decoded = runtime().block_on(roundtrip(&payload));
        prop_assert_eq!(decoded.as_ref(), payload.as_slice());
    }

    /// Payloads drawn only from `{0x00, 0xEB, 0x90, 0xFF}` so that the EB90 sync
    /// marker (0xEB 0x90) appears frequently inside the body. The framing must
    /// not mistake payload bytes for a frame boundary.
    #[test]
    fn roundtrips_marker_heavy_payload(
        payload in proptest::collection::vec(
            proptest::sample::select(vec![0x00u8, 0xEB, 0x90, 0xFF]),
            1..512,
        )
    ) {
        let decoded = runtime().block_on(roundtrip(&payload));
        prop_assert_eq!(decoded.as_ref(), payload.as_slice());
    }
}
